sudo: required
services:
  - docker

before_install:
  - docker build -t davidnymanibm/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run davidnymanibm/react-test npm test -- --coverage

after_success:
  - docker build -t davidnymanibm/multi-client:latest ./client --pull
  - docker build -t davidnymanibm/multi-nginx ./nginx
  - docker build -t davidnymanibm/multi-server ./server
  - docker build -t davidnymanibm/multi-worker ./worker
  - docker push davidnymanibm/multi-client:latest
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push davidnymanibm/multi-nginx
  - docker push davidnymanibm/multi-server
  - docker push davidnymanibm/multi-worker